### ISSUE TITLE
README.md needs small update

### ISSUE THREAD

**Issue by mmayo888** [JedS6391/LGP#25]
The command to run the example given in README.md is:
`kotlin -cp LGP.jar MyProblemKt`
I believe that it should be changed to:
`kotlin -cp LGP.jar:. MyProblemKt`
so that the MyProblemKt class can be found in the class path.

**Comment by JedS6391** [comment]
Thanks for pointing that out -- it seems those characters got lost somewhere along the way!

The README and usage documentation has been updated in the latest commit ( cc9d6e703ab7c56a0dce9a56ea20ee018942037c).
