### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by homonecloco** [JedS6391/LGP#55]
The following links are broken:

 *  https://lgp.readthedocs.io/en/latest/guide/environment.html from https://lgp.readthedocs.io/en/latest/guide/environment.html 
 * https://lgp.jedsimson.co.nz/api/html/lgp.core.evolution.population/-evolution-model/index.html from https://lgp.readthedocs.io/en/latest/guide/evolution.html 
* https://jeds6391.github.io/LGP/api/html/lgp.core.evolution/index.html from https://lgp.readthedocs.io/en/latest/guide/problem.html

Please review all the links to the API. They seem to be consistently broken

**Comment by JedS6391** [comment]
Hi @homonecloco, I have updated the links across the [documentation](https://lgp.readthedocs.io/en/latest/). I believe all the links should be OK now, but please let me know if I have missed any. 

I also reviewed the documentation content and made some minor adjustments where I felt it was necessary.
