### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by homonecloco** [JedS6391/LGP#56]
The required version of the JDK is not stated in the documentation.  This can be resolved by just stating the java version in the documentation (I had to update to java 1.8, as I had 1.7 installed). 

I'm following the instructions in https://github.com/JedS6391/LGP/tree/release/4.2 

However, kaitlin is not compiling the ```MyProble.kt```. I get the following issue:

```sh
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
$ kotlinc -cp LGP.jar -no-jdk -no-stdlib MyProblem.kt
MyProblem.kt:1:36: error: unresolved reference: Configuration
import lgp.core.environment.config.Configuration
                                   ^
MyProblem.kt:11:22: error: unresolved reference: Config
            config = Config()
                     ^
$ ls
10.21105.joss.01337.pdf	LGP.jar			MyProblem.kt
```

**Comment by JedS6391** [comment]
Hi @homonecloco,

Firstly, thanks for reviewing LGP for JOSS!

The documentation has been updated on the [master branch](https://github.com/JedS6391/LGP/tree/master) to reflect these API changes and should work as intended now.

Alternatively, the instructions in the [usage guide](https://lgp.readthedocs.io/en/latest/guide/usage.html) have some slightly more detailed steps for setting up the same example problem.

I have also added a note to both the README and the usage guide to indicate the required JDK/java version.

Please let me know if you are able to get the sample working correctly after these changes.

**Comment by homonecloco** [comment]
Thanks for the updates. I managed to make it run, but I think in the manual you still have something inconsisten, as I was unable to run the program with:

```sh
kotlinc -cp LGP.jar -no-jdk -no-stdlib MyProblem.kt
kotlin -cp LGP.jar:. MyProblemKt
```
I think it is because even renaming the LGP-core to LGP.jar is not enough. 

However, I did succeed to run 

```sh
# Compile to a JAR using kotlinc
kotlinc -cp LGP-core.jar:LGP-lib.jar -no-jdk -no-stdlib -d MyProblem.jar MyProblem.kt

# Use the Kotlin interpreter to execute the main function
kotlin -cp LGP-core.jar:LGP-lib.jar:MyProblem.jar:. MyProblemKt
```

**Comment by JedS6391** [comment]
Apologies, @homonecloco! 

Looks like I had missed a few updates. These inconsistencies should be resolved now with the latest commit on the `master` branch (b154c4313ed6f8d2a7eae06ee72cc922bfb774eb).
